// Copyright@Sdk2009
// Autogenerated from Pigeon (v22.6.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct User {
  var name: String
  var mobileNo: Int64



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> User? {
    let name = pigeonVar_list[0] as! String
    let mobileNo = pigeonVar_list[1] as! Int64

    return User(
      name: name,
      mobileNo: mobileNo
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      mobileNo,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Message {
  var content: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Message? {
    let content = pigeonVar_list[0] as! String

    return Message(
      content: content
    )
  }
  func toList() -> [Any?] {
    return [
      content
    ]
  }
}

private class UsersPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return User.fromList(self.readValue() as! [Any?])
    case 130:
      return Message.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class UsersPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? User {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? Message {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class UsersPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return UsersPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return UsersPigeonCodecWriter(data: data)
  }
}

class UsersPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = UsersPigeonCodec(readerWriter: UsersPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol UserHostApi {
  func getHostLanguage() throws -> String
  func saveUser(user: User, completion: @escaping (Result<Bool, Error>) -> Void)
  func getUser(completion: @escaping (Result<User, Error>) -> Void)
  func getAllUser(completion: @escaping (Result<[User], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class UserHostApiSetup {
  static var codec: FlutterStandardMessageCodec { UsersPigeonCodec.shared }
  /// Sets up an instance of `UserHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: UserHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getHostLanguageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_package.UserHostApi.getHostLanguage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getHostLanguageChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getHostLanguage()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getHostLanguageChannel.setMessageHandler(nil)
    }
    let saveUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_package.UserHostApi.saveUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveUserChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userArg = args[0] as! User
        api.saveUser(user: userArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveUserChannel.setMessageHandler(nil)
    }
    let getUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_package.UserHostApi.getUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUserChannel.setMessageHandler { _, reply in
        api.getUser { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getUserChannel.setMessageHandler(nil)
    }
    let getAllUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_package.UserHostApi.getAllUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllUserChannel.setMessageHandler { _, reply in
        api.getAllUser { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAllUserChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MessageHostApi {
  func sendMessage(message: Message) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MessageHostApiSetup {
  static var codec: FlutterStandardMessageCodec { UsersPigeonCodec.shared }
  /// Sets up an instance of `MessageHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MessageHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_package.MessageHostApi.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! Message
        do {
          try api.sendMessage(message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
  }
}
